The Last !!
DropEverythingOrg/DummyRepo pull request #39
Opened 2017-05-11 00:04 UTC by BachirC

@BachirC please ok ?

2017-05-11 00:04 UTC, BachirC commented
@BachirC nice diff !

2017-05-11 09:16 UTC, BachirC commented on sample.txt
> +Some text updated
k

2017-05-11 12:07 UTC, BachirC commented
@BachirC please

2017-05-11 12:10 UTC, BachirC commented on sample.txt
> +Some text updated
w

2017-05-11 12:11 UTC, BachirC commented on sample.txt
> +Some text updated
d

2017-05-11 12:16 UTC, BachirC commented
@BachirC ok ???

2017-05-11 12:32 UTC, BachirC commented
@BachirC Really ?

2017-05-11 12:35 UTC, BachirC commented
C'est la derniere fois ! @Bachir

2017-05-11 12:36 UTC, BachirC commented
@BachirC where is it ?

2017-05-11 12:37 UTC, BachirC commented
Allright, allright @BachirC.

2017-05-11 12:38 UTC, BachirC commented
Allright, allright @BachirC

2017-05-11 13:10 UTC, BachirC commented on sample.txt
> +Some text updated
w

2017-05-11 15:47 UTC, BachirC commented on sample.txt
> +Some text updated
ddd

2017-05-11 15:50 UTC, Mszniber requested changes
I REQUEST A CHANGE

2017-05-11 15:50 UTC, Mszniber commented on sample.txt
> +Some text updated
You sure it's the last ? :p

2017-05-11 15:54 UTC, BachirC commented on sample.txt
> +Some text updated
www

2017-05-11 15:56 UTC, BachirC reviewed
You suck man, please make it better

2017-05-11 15:56 UTC, BachirC commented on sample.txt
> +Some text updated
ee

2017-05-11 15:57 UTC, BachirC reviewed
Suck to be you bro !

2017-05-11 15:57 UTC, BachirC commented on sample.txt
> +Some text updated
www

2017-05-11 15:59 UTC, Mszniber requested changes
I REQUEST A CHANGE

2017-05-11 16:00 UTC, BachirC commented on sample.txt
> +Some text updated
ww

2017-05-11 16:01 UTC, BachirC reviewed
Good stuff, good stuff !!!!!

2017-05-11 16:01 UTC, BachirC commented on sample.txt
> +Some text updated
wewe

2017-05-11 16:07 UTC, BachirC commented on sample.txt
> +Some text updated
wewe

2017-05-11 16:08 UTC, BachirC reviewed
C'est pas mal tout ca ! LGTM 👍

2017-05-11 16:08 UTC, BachirC commented on sample.txt
> +Some text updated
w

2017-05-11 16:09 UTC, BachirC reviewed
Not bad, not bad ! 👍

2017-05-11 16:09 UTC, BachirC commented on sample.txt
> +Some text updated
w

2017-05-11 16:10 UTC, BachirC commented on sample.txt
> +Some text updated
w

2017-05-12 07:36 UTC, BachirC reviewed
Well played man ! @BachirC

2017-05-12 07:36 UTC, BachirC commented on sample.txt
> +Some text updated
www

2017-05-12 07:37 UTC, BachirC reviewed
OK @BachirC

2017-05-12 07:37 UTC, BachirC commented on sample.txt
> +Some text updated
sdsd

2017-05-12 07:40 UTC, BachirC reviewed
Tres bon ca @BachirC

2017-05-12 07:40 UTC, BachirC commented on sample.txt
> +Some text updated
ok ok ok

2017-05-12 07:44 UTC, BachirC commented on sample.txt
> +Some text updated
w

2017-05-12 07:45 UTC, BachirC commented on sample.txt
> +Some text updated
d

2017-05-12 07:54 UTC, BachirC reviewed
@BachirC this is nice

2017-05-12 07:54 UTC, BachirC commented on sample.txt
> +Some text updated
hello @BachirC

2017-05-12 07:55 UTC, BachirC commented
@BachirC this is some nice stuff

2017-05-12 08:27 UTC, BachirC commented
@BachirC ok ?

2017-05-12 12:31 UTC, BachirC commented on sample.txt
> +Some text updated
okok

2017-05-12 12:31 UTC, BachirC reviewed
yes ?

2017-05-12 12:31 UTC, BachirC commented on sample.txt
> +Some text updated
okkk

2017-05-12 13:40 UTC, BachirC commented
@BachirC, ok you got it

2017-05-12 13:42 UTC, BachirC commented
@BachirC, ok ok

2017-05-12 13:42 UTC, BachirC commented
@Bach-irC ok

2017-05-12 13:50 UTC, BachirC commented
@BachirC, ok ok we get it

2017-05-12 13:59 UTC, BachirC reviewed
@BachirC, with a comment

2017-05-12 13:59 UTC, BachirC commented on sample.txt
> +Some text updated
@BachirC, with a comment

2017-05-12 14:00 UTC, BachirC commented on sample.txt
> +Some text updated
ok

2017-05-12 14:03 UTC, BachirC commented
@BachirC, with a comment

2017-05-12 14:03 UTC, closed without merging