More dummy text
DropEverythingOrg/DummyRepo pull request #58
Opened 2017-05-16 18:50 UTC by BachirC

2017-05-17 11:05 UTC, BachirC commented
@BachirC

2017-05-17 11:45 UTC, BachirC commented
@BachirC

2017-05-17 18:20 UTC, BachirC commented
@BachirC

2017-05-17 18:21 UTC, BachirC commented
@BachirC

2017-05-17 18:23 UTC, BachirC commented
@BachirC

2017-05-17 21:32 UTC, BachirC commented
@BachirC !!!!!!!!!

2017-05-17 21:41 UTC, BachirC commented
@BachirC

2017-05-17 23:15 UTC, BachirC commented
@BachirC

2017-05-17 23:16 UTC, BachirC commented
@BachirC

2017-05-17 23:19 UTC, BachirC commented
@BachirC

2017-05-17 23:22 UTC, BachirC commented
@BachirC

2017-05-17 23:25 UTC, BachirC commented
@BachirC

2017-05-17 23:28 UTC, BachirC commented
@BachirC

2017-05-18 05:41 UTC, remimeunier requested changes

2017-05-18 05:41 UTC, remimeunier commented on sample.txt
> +Some text updated
Mais c'est qui cette merde, tu me refais ça @BachirC

2017-05-18 05:41 UTC, remimeunier commented on sample.txt
> +Some text updated
*quoi

2017-05-18 08:15 UTC, BachirC commented
@BachirC

2017-05-18 08:16 UTC, BachirC commented
@BachirC

2017-05-18 08:17 UTC, BachirC commented
@BachirC

2017-05-18 08:19 UTC, BachirC commented
@BachirC

2017-05-18 08:20 UTC, BachirC commented
@BachirC

2017-05-18 08:23 UTC, BachirC commented
@BachirC

2017-05-18 08:31 UTC, BachirC commented
@BachirC

2017-05-18 12:17 UTC, BachirC commented on sample.txt
> +Some text updated
Desole

2017-05-18 12:18 UTC, BachirC commented on sample.txt
> +Some text updated
Ok

2017-05-18 12:26 UTC, BachirC commented
@remimeunier PD

2017-05-18 18:11 UTC, BachirC commented
@BachirC

2017-05-18 18:12 UTC, BachirC commented
@BachirC

2017-05-18 18:12 UTC, BachirC commented
@BachirC

2017-05-18 18:14 UTC, BachirC commented
@BachirC

2017-05-18 19:29 UTC, BachirC commented
@BachirC

2017-05-19 17:33 UTC, BachirC commented
@BachirC

2017-05-19 17:34 UTC, BachirC commented
@BachirC

2017-05-19 17:34 UTC, BachirC commented
@BachirC

2017-05-21 20:53 UTC, BachirC commented
@BachirC

2017-05-21 22:46 UTC, BachirC commented
@BachirC

2017-05-21 22:47 UTC, BachirC commented
@BachirC

2017-05-22 11:23 UTC, BachirC commented
@BachirC

2017-05-22 11:24 UTC, BachirC commented
@BachirC

2017-05-23 22:53 UTC, BachirC commented
@BachirC

2017-05-23 22:54 UTC, BachirC commented
@BachirC

2017-05-23 22:57 UTC, BachirC commented
@BachirC

2017-05-23 22:58 UTC, BachirC commented
@BachirC

2017-05-23 22:58 UTC, BachirC commented
@BachirC

2017-05-23 22:59 UTC, BachirC commented
@BachirC

2017-05-23 23:00 UTC, BachirC commented
@BachirC

2017-05-23 23:03 UTC, BachirC commented
@BachirC

2017-05-23 23:10 UTC, BachirC reviewed
ok

2017-05-23 23:10 UTC, BachirC commented on sample.txt
> +Some text updated
kko

2017-05-23 23:13 UTC, BachirC commented on sample.txt
> +Some text updated
kkk

2017-05-23 23:36 UTC, BachirC commented
@BachirC

2017-05-23 23:44 UTC, BachirC commented on sample.txt
> +Some text updated
ok

2017-05-23 23:46 UTC, BachirC commented
@BachirC

2017-05-23 23:47 UTC, BachirC commented
@BachirC

2017-05-23 23:47 UTC, BachirC commented on sample.txt
> +Some text updated
ook

2017-05-23 23:59 UTC, BachirC commented
@BachirC

2017-05-23 23:59 UTC, BachirC commented
@BachirC

2017-05-24 00:00 UTC, BachirC commented
@BachirC

2017-05-29 17:44 UTC, BachirC commented
@BachirC

2017-05-29 17:44 UTC, BachirC commented on sample.txt
> +Some text updated
ok

2017-05-29 17:49 UTC, BachirC commented on sample.txt
> +Some text updated
ok

2017-05-29 17:49 UTC, BachirC commented
@BachirC

2017-05-29 17:50 UTC, BachirC commented on sample.txt
> +Some text updated
OK

2017-06-03 22:54 UTC, BachirC commented on sample.txt
> +Some text updated
l

2017-06-04 00:19 UTC, BachirC commented
@BachirC ?????

2017-06-04 00:21 UTC, BachirC commented
@BachirC

2017-06-04 01:04 UTC, BachirC commented
@BachirC

2017-06-04 01:06 UTC, BachirC commented
@BachirC

2017-06-04 01:06 UTC, BachirC commented
@BachirC

2017-06-04 01:07 UTC, BachirC commented
@BachirC

2017-06-04 01:07 UTC, BachirC commented
@BachirC

2017-06-04 01:08 UTC, BachirC commented on sample.txt
> +Some text updated
d

2017-06-04 01:52 UTC, BachirC commented
@BachirC

2017-06-04 12:25 UTC, BachirC commented
@BachirC

2017-06-05 11:51 UTC, BachirC commented
@BachirC

2017-06-05 11:55 UTC, BachirC commented on sample.txt
> +Some text updated
k

2017-06-07 11:11 UTC, Mszniber requested changes
C'est quoi ce taf tout pourri

2017-06-07 11:12 UTC, remimeunier requested changes
Cleaner code will be better. Otherwise it's okay. good job.

2017-06-07 11:12 UTC, remimeunier commented on sample.txt
> +Some text updated
Please use rubocop

2017-06-07 11:14 UTC, Mszniber approved these changes
Seems like it's working

2017-06-07 11:16 UTC, BachirC commented
@BachirC

2017-06-07 11:19 UTC, remimeunier requested changes
This will create N+1 querry. Please fix.

2017-06-07 11:19 UTC, remimeunier commented on sample.txt
> +Some text updated
This will create N+1 querry. Please fix.

2017-06-07 11:20 UTC, Mszniber approved these changes
Great fix, thanks a lot :+1:

2017-06-07 11:21 UTC, remimeunier approved these changes
This should work well. Good job son.

2017-06-07 11:22 UTC, closed without merging